### ISSUE TITLE
Push 0.18 changes to Eclipse.

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/CIHM-Meta#2]
I've made minor changes to Press that need to be run on things.

**Comment by RussellMcOrmond** [comment]
Notes are in https://github.com/crkn-rcdr/Systems-Administration/wiki/Pinto (Staff access only)

I've added that module version to our Pinto -- did you want me to build the container/etc?

/etc/canadiana/docker-pinto pinto add --author CIHM  /pinto/deploy/CIHM-Meta-0.18.tar.gz

**Comment by SaschaAdler** [comment]
Go for it, if you have time.

-Sascha
________________________________

**Comment by RussellMcOrmond** [comment]
docker.c7a.ca/cihm-metadatabus:20190308 is the image now run on Eclipse.
