### ISSUE TITLE
Clean up unnecessary references to things no longer in use

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/CIHM-Meta#3]

**Comment by RussellMcOrmond** [comment]
Is this https://github.com/crkn-rcdr/cihm-metadatabus/commit/3819ddb80cd168f6bd64febe687f8e84fa99f90f ?

Or is this about module testing, or...?

**Comment by RussellMcOrmond** [comment]
Some subtasks:

* CIHM::TDR::TDRConfig to be replaced with direct use of Config::General
* CIHM::TDR::Repository referenced by Hammer, but is it still used?
* Should be moved to CIHM::Meta , as the metadatabus is the home of these couch databases
    * CIHM::TDR::REST::filemeta
    * CIHM::TDR::REST::internalmeta
    * CIHM::TDR::REST::externalmeta
    * CIHM::TDR::REST::cosearch
    * CIHM::TDR::REST::copresentation
    * CIHM::TDR::REST::dipstaging
* remove CIHM::Meta::SipValidate which did special SIP validation against all ingested AIPs (if tool is recreated in future for some reason, would be part of CIHM::TDR)
