### ISSUE TITLE
Minor schema issue re: updates

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/CIHM-Meta#30]
When inserting a pdf manifest into the Access-Platform fixtures, I found that it wasn't validating. The issue was that the boolean `succeeded` field in the `updateInternalmeta` object was being set to `1` instead of `true`. I believe the perl JSON module has some way of ensuring that booleans are set to `true` or `false` in the JSON output (something like using `JSON::true` instead of `1`).

This doesn't make a difference for code that references the object and so it's a very low priority, but perhaps worth looking into at some point (and for future updates that aren't internalmeta).

**Comment by RussellMcOrmond** [comment]
Adjusted for Hammer2, but will leave open as a reminder to look at all the other similar booleans.

Status views show the old documents that were not updated....

* https://admin.canadiana.ca/couchview/collection/metadatabus/updateinternalmetas?group=2&keytype=json&reduce=true
* https://admin.canadiana.ca/couchview/manifest/metadatabus/updateinternalmetas?group=2&keytype=json&range=false&reduce=true

**Comment by RussellMcOrmond** [comment]
The `collection` and `manifest` databases are gone, so closing this issue.  If there are still other boolean fields that have numbers, we can open new tickets.

**Comment by SaschaAdler** [comment]
It's the only one I've run across.
