### ISSUE TITLE
canonicalDownload component PDFs not passed down to copresentation2

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/CIHM-Meta#31]
The filename for single-page component PDFs isn't passed into the manifest's `components` object in `copresentation2`. Compare [`copresentation`](http://iris.tor.c7a.ca:5984/copresentation/oocihm.8_06929_36) to [`copresentation2`](http://iris.tor.c7a.ca:5984/copresentation2/oocihm.8_06929_36).

Not a huge priority for the moment, but is technically a regression for LoP, until we manage to come up with a better PDF system. If there's a better way to generate Swift download links for these PDFs, I can do it from within CAP instead.

**Comment by RussellMcOrmond** [comment]
Oops.   Jumped the gun to when we won't need the paths.   In the future the individual and PDFs will be in Swift associated with the NOID, but that hasn't been done yet.

Will fix this up early next week (once the Swift/networking issue is resolved).

**Comment by RussellMcOrmond** [comment]
I created https://github.com/crkn-rcdr/Access-Platform/issues/63 as I suspect it makes sense for us to start to solidify our planning, and initiate some of the copying into the access platform Swift containers.

**Comment by RussellMcOrmond** [comment]
When I launched Hammer2 to run on all manifests, a bad assumption was detected and fixed d606651183a99ddfb181caab95baa153cdf6f922 

This is now processing in the background.  I will close, and this can be re-opened if there is an additional issue.
