### ISSUE TITLE
loadseries: do not operate on parl-only series records

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/CIHM-Meta#32]
We don't use the series records that were created for `parl` content any more, and so it would be helpful to avoid later cleanup if they aren't imported into the new collection database. There are 6 series that are part of `parl` and also `govpubs`, `online`, etc. which should still be imported as part of those collections (they don't need to be part of `parl`, though). Every series that is only part of `parl` can be ignored.

**Comment by RussellMcOrmond** [comment]
Are we planning on clearing the `collection` database, or having staff use tools to get it into the condition they want? I'm been assuming the latter.

I think we need to create a view to find collections that are only in the `parl` collection and determine which ones we want to clean out.  If it is seen as helpful we can update loadseries to not add them back.

I will want to generate the list and confirm with you what the intention is.  We will want to ensure the public flag is unset and any derived documents (`internalmeta2` , `cosearch2`, `copresentation2`) are deleted.

**Comment by SaschaAdler** [comment]
[Here you go.](http://iris.tor.c7a.ca:8983/solr/cosearch/select?q=collection:parl+AND+depositor:oop&fq=type:series&rows=1000&fl=key&wt=csv&indent=true)

**Comment by RussellMcOrmond** [comment]
Thanks.  I'm going to create a few design/cleanup views for the databases to help us in any later cleanup once we no longer run the tool.  It will also help me with any testing of updates to `loadseries`.

Anything else we think of we can do similar, and then remove those views once we have flipped the switch the final time.

**Comment by RussellMcOrmond** [comment]
I should have guessed....

```
russell@russell-XPS-13-7390:~/git/Systems-Administration/couch-scripts$ ./parl-cleanup
Only in Couch: 
Only in Solr: oop.journals_CDC oop.journals_HOC oop.journals_SDC oop.journals_SOC
russell@russell-XPS-13-7390:~/git/Systems-Administration/couch-scripts$ 
```

These aren't series records at all, but will also need to be cleaned up as I believe they will be redundant.

My preference is to leave these records alone for now, and clean up after the last time that `loadseries` is run -- which will hopefully not be too long from now.

**Comment by SaschaAdler** [comment]
Those four jerk "document" series records have been messing with us for years.

**Comment by RussellMcOrmond** [comment]
Final cleanup work references in https://github.com/crkn-rcdr/Access-Platform/issues/97 .  This issue can be closed, but still used for notes to remind us about the problem.
