### ISSUE TITLE
Press: provide canonicalDownload as well as canonicalMaster for items with per-page PDFs

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/CIHM-Meta#8]
Currently Press provides a component's canonicalMaster in an item's components object. If we also provide canonicalDownload when it exists, I can create single-page PDF download links without making some horrendous assumptions about whether the file path exists and what it looks like.

Checking if 
* the item doesn't have a canonicalMaster itself (and would therefore be a born-digital PDF)
* the item doesn't have a canonicalDownload
* the item has a `component_count_fulltext` field, meaning that OCR has run on it

works for now, but is hacky, as is renaming the file extension of the component canonicalMaster to .pdf.

**Comment by RussellMcOrmond** [comment]
Please confirm if https://upholstery.canadiana.ca/_utils/document.html?copresentation/oop.bills_SOCHOC_0901_1 is what you were thinking of.   If so, then we can update https://crkn.sharepoint.com/:x:/s/platform/Ed9hL3v-q_xMr9XGgMAd9s0BB0LrkwZjc8Ao_9IE4FkBXg?e=grTkdk , and I can force press to re-run on all identifiers.

**Comment by SaschaAdler** [comment]
This looks good.

**Comment by RussellMcOrmond** [comment]
I've pushed an updated version of the metadatabus, and am now running the script that will cause press to re-run on all IDs.

**Comment by RussellMcOrmond** [comment]
I believe this is complete and can be confirmed?

**Comment by SaschaAdler** [comment]
Yes, I've made the switch in CAP to use this.
